### ISSUE TITLE
Testar possíveis tecnologias e padrões para IoT

### ISSUE THREAD

**Issue by ghost** [feira-de-jogos/nuvem#6]
Testar, além de MQTT, possíveis tecnologias e padrões para conectar embarcados, e IoT em geral, na plataforma unificada deste projeto, que já contemplará HTTPS.

**Comment by leojungneves** [comment]
Vou deixar alguns links úteis que ensinam a usar websocket com rasp e esp

1- Como criar um servidor de websocket para arduino(esp-32): 
     https://www.youtube.com/watch?v=ZbX-l1Dl4N4&t=143s
2- Integração de um servidor web com Esp-32, usando websocket:
     https://www.youtube.com/watch?v=mkXsmCgvy0k&t=367s
3- Servidor web com websocket para outros programas controlarem uma rasp usando Node JS(toda a documentação e códigos na descrição:
     https://www.youtube.com/watch?v=YvsOUkTUsxg

**Comment by ghost** [comment]
De acordo com #1, o sistema foi atualizado. O sistema usará REST API + JSON, sem a necessidade de MQTT ou WebSockets.
